name: Laravel

on: [push]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: 'Setup PHP'
      uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '8.0'
    - name: 'Setup Node'
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - uses: actions/checkout@v2
    - name: 'Copy .env'
      run: cp .env.github .env
    - name: 'Create Database'
      run: |
        sudo systemctl start mysql
        mysql --user="root" --password="root" -e "CREATE DATABASE expeditiekaart character set UTF8mb4 collate utf8mb4_bin;"
    - name: 'Install Composer Dependencies'
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: 'Install Node Dependencies'
      run: npm ci
    - name: 'Setup Cypress'
      run: |
        npx cypress install
        npx cypress verify
        npx cypress info
        npx cypress version
        php cypress-api.php
#    - name: 'Run Laravel Mix'
#      run: npm run production
    - name: 'Generate key'
      run: php artisan key:generate
    - name: 'Link Storage'
      run: php artisan storage:link
    - name: 'Directory Permissions'
      run: chmod -R 777 storage bootstrap/cache
    - name: 'Run Unit Tests'
      run: vendor/bin/phpunit
#    - name: 'Run Laravel Server'
#      run: php artisan serve &
    - name: 'Get current date'
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%I%S')"
#    - name: 'Run Cypress Tests'
#      run: npx cy2 run --parallel --record --key ${{ secrets.CYPRESS_KEY }} --ci-build-id ${{ github.run_id }}-${{ steps.date.outputs.date }}
#      env:
#        CYPRESS_API_URL: ${{ secrets.CYPRESS_API_URL }}
    - name: 'Run Cypress Tests'
      uses: cypress-io/github-action@v2
      with:
        install: false
        build: npm run production
        start: php artisan serve
        record: true
        parallel: true
        ci-build-id: ${{ github.run_id }}-${{ steps.date.outputs.date }}
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
        CYPRESS_API_URL: ${{ secrets.CYPRESS_API_URL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

